export var sync_button = [
    "active:from-cyan-600",
    "active:to-orange-600",
    "bg-gradient-to-r",
    "duration-300",
    "ease-out",
    "font-semibold",
    "from-indigo-500",
    "hover:shadow-pink-500/40",
    "hover:shadow-sm",
    "items-center",
    "justify-center",
    "px-6",
    "py-3",
    "rounded-2xl",
    "shadow-indigo-500/30",
    "shadow-xs",
    "text-white",
    "to-pink-500",
    "transition-all",
    "via-purple-500",
    "w-full flex",
];